modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="eternalartifacts"
version="1.0.0"
displayName="Eternal Artifacts"
logoFile="logo.png"
authors="SonaMorningstar"
description='''
    Adds various artifacts and gadgets to enhance your minecraft experience.
'''

[[dependencies.eternalartifacts]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.eternalartifacts]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
   config = "eternalartifacts.mixins.json"

